import type { Actor, ActPayload, ActorMode } from '../interfaces/actor';

/**
 * ClickActor — Execution strategy for 'auto' mode.
 *
 * Simulates a realistic, hardware-accurate user selection by dispatching
 * a full 5-stage native event lifecycle on the chosen quiz option DOM element.
 *
 * ## Why not plain `element.click()`?
 * While `target.click()` fires a solitary `click` event, modern Single-Page
 * Applications (SPAs) and accessible design systems (e.g. React Aria, Radix UI,
 * Ant Design, Material-UI) do not rely solely on `click`. Many component libraries,
 * gesture handlers, and interaction Finite State Machines (FSMs) track
 * `pointerdown` and `mousedown` states to:
 * 1. Disambiguate clicks from drags/scrolls (e.g. measuring displacement between down and up).
 * 2. Track input modality (mouse vs keyboard vs assistive screen reader).
 * 3. Transition internal interaction state machines (e.g. `Idle -> Pressed -> Selected`).
 *
 * Dispatching the complete chronological sequence ensures the simulated click is
 * accepted across complex UI components without being dropped or ignored.
 */
export class ClickActor implements Actor {
  readonly mode: ActorMode = 'auto';

  /**
   * Dispatches the 5-event synthetic click sequence on the solver's chosen option.
   *
   * @param payload - Contains the extracted quiz data (including DOM elements) and solver result.
   */
  async act(payload: ActPayload): Promise<void> {
    // 1. Resolve Target Element
    // Locate the exact DOM container corresponding to the AI's chosen option index.
    const target = payload.quiz.optionElements[payload.result.chosenIndex];
    if (!target) return; // Guard against out-of-bounds or missing DOM nodes.

    // 2. Window Resolution & Browsing Context
    // Determine the appropriate Window context from first principles:
    // - In a real browser tab, `window` is the global execution context.
    // - If the target element is embedded in an `<iframe>` (common in classroom/video UIs),
    //   `target.ownerDocument?.defaultView` retrieves that specific iframe's `Window` context.
    // - In headless test runners (e.g. Node.js + JSDOM), `window` may not be bound globally,
    //   so `typeof window !== 'undefined'` avoids ReferenceErrors.
    const win = (typeof window !== 'undefined' ? window : target.ownerDocument?.defaultView) as Window | undefined;

    // 3. Event Configuration
    // - `bubbles: true`: CRITICAL for React. React attaches its SyntheticEvent listeners
    //   at the root container (#root / document) using event delegation. Non-bubbling events
    //   would never propagate up to React's root listener.
    // - `cancelable: true`: Allows event handlers to call `e.preventDefault()`, matching native clicks.
    // - `view: win`: Links the event to the active browsing context / window viewport.
    // - `button: 0`: Specifies the primary (left) mouse button (0: left, 1: middle, 2: right).
    const eventOpts: MouseEventInit = { bubbles: true, cancelable: true, view: win, button: 0 };

    // 4. PointerEvent Specification Fallback
    // W3C Pointer Events unify Mouse, Touch, and Stylus inputs under a single API
    // and inherit from MouseEvent (`Event -> UIEvent -> MouseEvent -> PointerEvent`).
    // All modern browsers natively support PointerEvent. We provide a fallback to MouseEvent
    // for headless testing environments (e.g. JSDOM) where PointerEvent may not be defined.
    const PointerEventCtor = typeof PointerEvent !== 'undefined' ? PointerEvent : (MouseEvent as any);

    // 5. Chronological 5-Stage Native Event Sequence
    // Replicates the exact physical sequence generated by a browser engine during a human click:
    //   1. pointerdown — Contact initiated (Pointer Events API).
    //   2. mousedown   — Legacy mouse down; triggers press states, focus, and ripple effects.
    //   3. pointerup   — Contact released (Pointer Events API).
    //   4. mouseup     — Legacy mouse up; completes the down/up gesture pair.
    //   5. click       — High-level semantic activation fired when down/up occur on the same target.
    target.dispatchEvent(new PointerEventCtor('pointerdown', eventOpts));
    target.dispatchEvent(new MouseEvent('mousedown', eventOpts));
    target.dispatchEvent(new PointerEventCtor('pointerup', eventOpts));
    target.dispatchEvent(new MouseEvent('mouseup', eventOpts));
    target.dispatchEvent(new MouseEvent('click', eventOpts));
  }

  /**
   * Cleanup lifecycle hook.
   *
   * Unlike `HudActor` (which modifies inline styles and must revert them),
   * `ClickActor` only dispatches transient DOM events and leaves no ongoing
   * mutations on the target elements, so cleanup is a clean no-op.
   */
  cleanup(): void {}
}
